### ISSUE TITLE
Add new syntax for redesign

### ISSUE THREAD

**Issue by bobgru** [MackeyRMS/sphinxesc#1]
Recognize `tag:` as a synonym for `@tag_list`. If multiple `tag:` keywords are used, combine their target strings into a parenthesized list of alternatives. Accept a quoted string as a `tag:` target.

For example:

```
tag:foo xxx tag:"bar zot" yyy
```

would become

```
(@tag_list foo|@tag_list "bar zot") xxx yyy
```

**Comment by kanishka-azimi** [comment]
Moved this elsewhere
